#!/usr/bin/env bash
# This script will ping an IP address 5 times
# Check if no argument is passed
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# IP address passed as argument
ip_address=$1

# Ping the IP address 5 times
ping -c 5 $ip_address
